package com.minderliu.entity;

public class FundKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.fundCode
     *
     * @mbggenerated
     */
    private String fundcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbggenerated
     */
    public FundKey(Integer id, String fundcode) {
        this.id = id;
        this.fundcode = fundcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.id
     *
     * @return the value of fund.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.fundCode
     *
     * @return the value of fund.fundCode
     *
     * @mbggenerated
     */
    public String getFundcode() {
        return fundcode;
    }
}