package com.minderliu.entity;

public class Fund extends FundKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.fundName
     *
     * @mbggenerated
     */
    private String fundname;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbggenerated
     */
    public Fund(Integer id, String fundcode, String fundname) {
        super(id, fundcode);
        this.fundname = fundname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.fundName
     *
     * @return the value of fund.fundName
     *
     * @mbggenerated
     */
    public String getFundname() {
        return fundname;
    }
}