package com.minderliu.dao;

import com.minderliu.entity.Fund;
import com.minderliu.entity.FundKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

@Repository
public interface FundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbggenerated
     */
    @Delete({
        "delete from fund",
        "where id = #{id,jdbcType=INTEGER}",
          "and fundCode = #{fundcode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(FundKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbggenerated
     */
    @Insert({
        "insert into fund (id, fundCode, ",
        "fundName)",
        "values (#{id,jdbcType=INTEGER}, #{fundcode,jdbcType=VARCHAR}, ",
        "#{fundname,jdbcType=VARCHAR})"
    })
    int insert(Fund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbggenerated
     */
    int insertSelective(Fund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, fundCode, fundName",
        "from fund",
        "where id = #{id,jdbcType=INTEGER}",
          "and fundCode = #{fundcode,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Fund selectByPrimaryKey(FundKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbggenerated
     */
    @Update({
        "update fund",
        "set fundName = #{fundname,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}",
          "and fundCode = #{fundcode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Fund record);
}